### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by JasonJAyalaP** [nullpo-head/Windows-10-Virtual-Desktop-Switching-Shortcut#1]
Says "Error. Some Error Occurred. Possible API Change" now.

**Comment by mzomparelli** [comment]
Can you provide your Windows build version? Unless you are using a super recent insider version then your error is not related to an API change.

**Comment by nullpo-head** [comment]
HI, this tool should not be working anymore due to the change of some internal constant value.  
I recommend to use [Win10 Virtual Desktop Enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer) instead. Although Win10 VDE's repository is archived, it works as long as you replace its `virtual-desktop-accessor.dll` with the latest one, which you can get from [the repository of VirtualDesktopAccessor](https://github.com/Ciantic/VirtualDesktopAccessor).

**Comment by mzomparelli** [comment]
Or this, which is actually the best you can get right now. Worth the money.

https://github.com/mzomparelli/zVirtualDesktop

**Comment by mzomparelli** [comment]
Also view the wiki to see updated Windows 10 Interface changes.

https://github.com/mzomparelli/zVirtualDesktop/wiki
