### ISSUE TITLE
fails on fresh insider build Version 10.0.19041.1

### ISSUE THREAD

**Issue by CoolCold** [nullpo-head/Windows-10-Virtual-Desktop-Switching-Shortcut#2]
---------------------------
VirtualDesktopSwitcher.exe - System Error
---------------------------
The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

build is : Microsoft Windows [Version 10.0.19041.1]

**Comment by nullpo-head** [comment]
HI, this tool should not be working anymore due to the change of some internal constant value.  
I recommend to use [Win10 Virtual Desktop Enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer) instead. Although Win10 VDE's repository is archived, it works as long as you replace its `virtual-desktop-accessor.dll` with the latest one, which you can get from [the repository of VirtualDesktopAccessor](https://github.com/Ciantic/VirtualDesktopAccessor).
